# Generated by Django 3.0 on 2021-12-27 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NftType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_type', models.SmallIntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=250)),
                ('nft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.NftType')),
            ],
        ),
        migrations.CreateModel(
            name='TradeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.SmallIntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_success_time', models.BigIntegerField()),
                ('price', models.CharField(max_length=250)),
                ('product_i', models.BigIntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Buyer')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Currency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Product')),
                ('trade_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.TradeType')),
            ],
        ),
    ]
